# Generated by Django 5.2.8 on 2025-11-27 19:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPOI',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('location_desc', models.TextField(null=True)),
            ],
            options={
                'db_table': 'custom_poi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmPoint',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'planet_osm_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmPolygon',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'planet_osm_polygon',
                'managed': False,
            },
        ),
    ]
